version: '3'

services:
  webserver:
    image: nginx:alpine
    container_name: static_web
    restart: unless-stopped
    ports:
      - "2443:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    user: root
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
