services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    entrypoint: >
      sh -c "
      ls -la /usr/share/nginx/html &&
      echo '<!DOCTYPE html><html><body><h1>Test Page</h1></body></html>' > /usr/share/nginx/html/test.html &&
      exec nginx -g 'daemon off;'"
    restart: unless-stopped
