version: '3'

services:
  webserver:
    image: caddy:2-alpine
    container_name: static_web
    restart: unless-stopped
    ports:
      - "2443:80"
    volumes:
      - ./html:/srv
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
