
services:
  webserver:
    image: caddy:2-alpine
    container_name: static_web
    restart: unless-stopped
    ports:
      - "2443:80"
    volumes:
      - ./html:/usr/share/caddy
    command: caddy run --config /etc/caddy/Caddyfile
    environment:
      - CADDY_CONTENT: |
        :80 {
            root * /usr/share/caddy
            file_server
            encode gzip
        }
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
