
services:
  app:
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # تغییر به پورتی که سرور شما روی آن اجرا می‌شود
    volumes:
      - ./app:/app # سینک کردن پوشه `app` در سیستم میزبان با کانتینر
    working_dir: /app
    command: ["node", "server.js"]
    environment:
      NODE_ENV: development
    restart: always
