version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: static_website
    ports:
      - "5442:5442"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./styles:/usr/share/nginx/html/styles
      - ./scripts:/usr/share/nginx/html/scripts
    restart: always
