services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: >
      /bin/sh -c "echo 'server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        location / {
          try_files \$uri \$uri/ /index.html;
          autoindex on;
          autoindex_exact_size off;
          autoindex_format html;
          autoindex_localtime on;
        }
      }' > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    restart: unless-stopped
