version: '3'

services:
  webserver:
    image: nginx:alpine
    container_name: static_web
    restart: unless-stopped
    ports:
      - "2443:2443"  # پورت 2443 تنظیم شده
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
