version: '3'

services:
  web:
    image: nginx:alpine
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
