version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: static_website
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro   # اتصال فایل
    restart: always
