version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"  # تغییر پورت از 80 به 8080
    volumes:
      - ./:/usr/share/nginx/html  # مسیر فایل‌های استاتیک
    restart: unless-stopped
