services:
  app:
    container_name: static-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2443:2443"
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "start"]
    restart: unless-stopped
    environment:
      NODE_ENV: production
