services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    working_dir: /usr/share/nginx/html
    volumes:
      - type: bind
        source: .
        target: /usr/share/nginx/html
    command: |
      sh -c "echo '
      server {
          listen 80;
          server_name localhost;
          
          root /usr/share/nginx/html;
          index index.html index.htm;
          
          location / {
              autoindex on;
              try_files $$uri $$uri/ /index.html;
              add_header Access-Control-Allow-Origin *;
          }
      }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: unless-stopped
