services:
  webserver:
    image: node:alpine
    container_name: static_web
    working_dir: /app
    ports:
      - "2443:3000"
    volumes:
      - ./app:/app
    command: ["node", "server.js"]
    restart: unless-stopped
