version: '3.8'
services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expressjs-html-app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
